### ISSUE TITLE
The payara-micro variable replacement is resolve twice.

### ISSUE THREAD

**Issue by charleech** [charleech/payara-evaluation#25]
### Summary
Try to implement the preboot and postboot script for supporting database configuration creation and testing during starting up the **Payara: Micro** by using the variable reference: -

* [Types of variable references](https://docs.payara.fish/community/docs/5.2020.5/documentation/payara-server/server-configuration/var-substitution/types-of-variables.html)
* [Using variable references](https://docs.payara.fish/community/docs/5.2020.5/documentation/payara-server/server-configuration/var-substitution/usage-of-variables.html)
* [Running asadmin commands using Preboot and Postboot Scripts](https://docs.payara.fish/community/docs/5.2020.5/documentation/payara-micro/asadmin/pre-and-post-boot-scripts.html)
* [An Introduction to Connection Pools in Payara Server 5](https://blog.payara.fish/an-intro-to-connection-pools-in-payara-server-5)

I've found that the `variable references` works well, except it is placed at the end of the `subcommand`, i.e.

```bash
create-jdbc-connection-pool --datasourceclassname ${ENV=JDBC_DATASOURCE_CLASSNAME} \
  --restype javax.sql.XADataSource \
  --property url=${ENV=JDBC_URL}:user=${ENV=JDBC_USER}:password=${ENV=JDBC_PASSWORD} \
  ${ENV=JDBC_POOL_NAME}
```
Please note that all the command is the long single line and is separated to be a multi-line here for increasing the readability.

### Steps to reproduce

* The `docker-compose.yml`

```yml
version: '3'

services:
  payara:
    image: payara/micro:latest
    environment:
      - TZ=Asia/Bangkok
      - JDBC_URL=jdbc\:h2\:mem\:testdb
      - JDBC_USER=testuser
      - JDBC_PASSOWRD=testuser
      - JDBC_DATASOURCE_CLASSNAME=org.h2.jdbcx.JdbcDataSource
      - JDBC_JNDI_NAME=jdbc/testdb
      - JDBC_POOL_NAME=test-db-pool
      - JDBC_POOL_MIN=1
      - JDBC_POOL_MAX=10
    volumes:
      - ./boot-scripts:/opt/payara/resources/boot-scripts
    command:
      - --prebootcommandfile
      - '/opt/payara/resources/boot-scripts/pre-boot.txt'
      - --postbootcommandfile
      - '/opt/payara/resources/boot-scripts/post-boot.txt'
```

* The `preboot script`

```bash
create-jdbc-connection-pool --datasourceclassname ${ENV=JDBC_DATASOURCE_CLASSNAME} --restype javax.sql.XADataSource --property url=${ENV=JDBC_URL}:user=${ENV=JDBC_USER}:password=${ENV=JDBC_PASSWORD} ${ENV=JDBC_POOL_NAME}

set resources.jdbc-connection-pool.${ENV=JDBC_POOL_NAME}.steady-pool-size=${ENV=JDBC_POOL_MIN}

set resources.jdbc-connection-pool.${ENV=JDBC_POOL_NAME}.max-pool-size=${ENV=JDBC_POOL_MAX}

set resources.jdbc-connection-pool.${ENV=JDBC_POOL_NAME}.connection-validation-method=custom-validation

set resources.jdbc-connection-pool.${ENV=JDBC_POOL_NAME}.validation-classname=org.glassfish.api.jdbc.validation.H2ConnectionValidation

set resources.jdbc-connection-pool.${ENV=JDBC_POOL_NAME}.is-connection-validation-required=true

set resources.jdbc-connection-pool.${ENV=JDBC_POOL_NAME}.fail-all-connections=true

set resources.jdbc-connection-pool.${ENV=JDBC_POOL_NAME}.statement-leak-timeout-in-seconds=5

set resources.jdbc-connection-pool.${ENV=JDBC_POOL_NAME}.connection-leak-timeout-in-seconds=5

create-jdbc-resource --connectionpoolid ${ENV=JDBC_POOL_NAME} ${ENV=JDBC_JNDI_NAME}
```

* * The `postboot script`
```bash
list-jdbc-connection-pools

list-jdbc-resources

ping-connection-pool ${ENV=JDBC_POOL_NAME}
```

* Just start the _Payara Micro Docker_ by using this project `docker-compose.yml` as

```bash
docker-compose up -d && docker-compose logs --follow
```

### Example project
This project

* [payara-evaluation/payara-evaluation-docker/01-prepostboot/](https://github.com/charleech/payara-evaluation/tree/master/payara-evaluation-docker/01-prepostboot)

### What's the current *bug* behaviors?
The  `variable references` is resolved wrongly when it is at the end of the `subcommand`.

### What is the expected *correct* behavior?
The  `variable references` should be resolved properly.

### Relevant logs and/or screenshots
```bash
payara_1  | [2020-10-22T11:42:04.700+0700] [] [WARNING] [] [fish.payara.boot.runtime.BootCommand] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1603341724700] [levelValue: 900] [[
payara_1  |   Boot Command test-db-pooltest-db-pool failed Exception while executing command.
payara_1  | org.glassfish.api.admin.CommandException: Command lookup failed for command test-db-pooltest-db-pool
payara_1  |     at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.getParameters(CommandExecutorImpl.java:106)
payara_1  |     at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.executeCommand(CommandExecutorImpl.java:177)
payara_1  |     at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.run(CommandExecutorImpl.java:96)
payara_1  |     at fish.payara.boot.runtime.BootCommand.execute(BootCommand.java:69)
payara_1  |     at fish.payara.boot.runtime.BootCommands.executeCommands(BootCommands.java:136)
payara_1  |     at fish.payara.boot.runtime.BootCommands.executeCommands(BootCommands.java:130)
payara_1  |     at fish.payara.micro.impl.PayaraMicroImpl.bootStrap(PayaraMicroImpl.java:1045)
payara_1  |     at fish.payara.micro.impl.PayaraMicroImpl.create(PayaraMicroImpl.java:227)
payara_1  |     at fish.payara.micro.impl.PayaraMicroImpl.main(PayaraMicroImpl.java:214)
payara_1  |     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
payara_1  |     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
payara_1  |     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
payara_1  |     at java.lang.reflect.Method.invoke(Method.java:498)
payara_1  |     at fish.payara.micro.boot.loader.MainMethodRunner.run(MainMethodRunner.java:50)
payara_1  |     at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:114)
payara_1  |     at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:73)
payara_1  |     at fish.payara.micro.boot.PayaraMicroLauncher.create(PayaraMicroLauncher.java:88)
payara_1  |     at fish.payara.micro.boot.PayaraMicroLauncher.main(PayaraMicroLauncher.java:72)
payara_1  |     at fish.payara.micro.PayaraMicro.main(PayaraMicro.java:467)
payara_1  | ]]

```
